export const cuisineList = [
    "Amala and Ewedu",
    "Banga Soup with Starch",
    "Chin Chin",
    "Dodo (Fried Plantains)",
    "Egusi Soup",
    "Fisherman Soup",
    "Gizdodo (Gizzard and Plantains)",
    "Hausa Koko (Spiced Millet Porridge)",
    "Isi Ewu (Goat Head Soup)",
    "Jollof Rice",
    "Kilishi (Nigerian Beef Jerky)",
    "Lokashe (Nigerian Couscous)",
    "Moi Moi (Steamed Bean Pudding)",
    "Nkwobi (Spiced Cow Foot)",
    "Ogbono Soup",
    "Pepper Soup",
    "Quaker Oats Pap (Nigerian Style)",
    "Rice and Stew",
    "Suya (Spiced Grilled Meat)",
    "Tuwo Shinkafa (Rice Pudding)",
    "Ukwa (African Breadfruit)",
    "Vegetable Soup (Edikang Ikong)",
    "White Soup (Ofe Nsala)",
    "Yam and Egg Sauce",
    "Yam Porridge",
    "Zobo (Hibiscus Drink)"
];